#
# Makefile for the sensor hub.
#

ifeq ($(CONFIG_SENSORS_SSP_BBD),y)
obj-$(CONFIG_GALILEO)  += brcm/
obj-$(CONFIG_PULSE)  += brcm_pulse/
obj-$(CONFIG_RENAISSANCE)  += brcm_pulse/
obj-$(CONFIG_RENAISSANCE_CHUB)  += brcm_pulse/
endif
